#!/bin/sh


###################################################################################
# This custom test file is part of the Compleasy Lynis tests
#
# It will contain custom tests, which can be used to extend the functionality
# of Lynis.
#
# The following tests are included:
# - CUST-9000: Compleasy Lynis custom test ping. Just to know that the Compleasy
#              Lynis custom tests are enabled.
# - CUST-9010: Lynis systemd timer info. It will gather information about the Lynis
#              systemd timer.
# - CUST-9020: Antivirus version check. It will check the version of the installed
#              antivirus software and the last update.
# - CUST-9030: Custom test to check the status of the firewall.
#
###################################################################################

    # Add a new section to the screen output
    InsertSection "Compleasy custom tests"

#################################################################################
#
    # Test        : CUST-0010
    # Description : Compleasy Lynis custom test ping. Just to know that the Compleasy Lynis custom tests are enabled.

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    # --test-no   unique ID
    # --weight    L/M/H
    # --category  category (e.g. performance, privacy, security)
    Register --test-no CUST-9000 --weight L --network NO --category security --description "Compleasy custom tests status"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Checking if everything is OK..." --result "${STATUS_OK}" --color GREEN
        Report "compleasy_custom_tests=1"
        #Display --indent 4 --text "This shows one level deeper " --result "${STATUS_NO}" --color YELLOW
        #Display --indent 6 --text "And even deeper" --result "${STATUS_WARNING}" --color RED
    fi
#
#################################################################################
#
    # Test        : CUST-0010
    # Description : Lynis systemd timer info. It will gather information about the Lynis systemd timer.
    Register --test-no CUST-9010 --weight L --network NO --category security --description "Compleasy Lynis systemd timer info"

    LYNIS_TIMER="/etc/systemd/system/timers.target.wants/lynis.timer"

    if FileExists ${LYNIS_TIMER}; then
        LogText "Found Lynis systemd timer file: ${LYNIS_TIMER}"
        Display --indent 2 --text "Lynis systemd timer file" --result "${STATUS_OK}" --color GREEN
    else
        # Requisites not met, so we skip the test
        ReportWarning "${TEST_NO}" "Lynis systemd timer file not found" "${LYNIS_TIMER}" "text:Check if Lynis is installed"
        # Skip the test
        SKIPTEST=1
    fi

    SystemctlEnabled() {
        SYSTEMCTL_ENABLED=$(systemctl is-enabled $1)
        if [ "${SYSTEMCTL_ENABLED}" = "enabled" ]; then
            return 0
        else
            return 1
        fi
    }

    if [ ${SKIPTEST} -eq 0 ]; then

        # Check if the timer is enabled
        if SystemctlEnabled lynis.timer; then
            LogText "Lynis systemd timer is enabled"
            Display --indent 2 --text "Lynis systemd timer enabled" --result "${STATUS_OK}" --color GREEN
            Report "lynis_timer_enabled=1"
        else
            LogText "Lynis systemd timer is not enabled"
            Display --indent 2 --text "Lynis systemd timer not enabled" --result "${STATUS_WARNING}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "Enable the Lynis systemd timer"
            Report "lynis_timer_enabled=0"
        fi

        SystemctlRunning() {
            SYSTEMCTL_RUNNING=$(systemctl is-active $1)
            if [ "${SYSTEMCTL_RUNNING}" = "active" ]; then
                return 0
            else
                return 1
            fi
        }

        # Check if the timer is running
        if SystemctlRunning lynis.timer; then
            LogText "Lynis systemd timer is running"
            Display --indent 2 --text "Lynis systemd timer running" --result "${STATUS_OK}" --color GREEN
            Report "lynis_timer_running=1"
        else
            LogText "Lynis systemd timer is not running"
            Display --indent 2 --text "Lynis systemd timer not running" --result "${STATUS_WARNING}" --color YELLOW
            ReportSuggestion "${TEST_NO}" "Start the Lynis systemd timer"
            Report "lynis_timer_running=0"
        fi

        # Check timer period
        TIMER_PERIOD=$(grep -i "OnCalendar" ${LYNIS_TIMER} | cut -d'=' -f2)
        Display --indent 2 --text "Lynis systemd timer period" --result "${TIMER_PERIOD}" --color GREEN
        # Add value to the report
        Report "lynis_timer_period=${TIMER_PERIOD}"

        # Next trigger time
        # systemctl status lynis.timer | grep "Trigger:"
        # Output example: Trigger: Tue 2024-07-30 00:22:20 CEST; 7h left
        FULL_TRIGGER=$(systemctl status lynis.timer | grep "Trigger:")
        NEXT_TRIGGER=$(echo ${FULL_TRIGGER} | cut -d';' -f1 | cut -d':' -f2-)
        Display --indent 2 --text "Lynis systemd timer next trigger" --result "${NEXT_TRIGGER}" --color GREEN
        # Add value to the report
        Report "lynis_timer_next_trigger=${NEXT_TRIGGER}"

    fi
    
#
#################################################################################
#
    # Test        : CUST-0010
    # Description : Anti-virus version and last update check

    # First check if ClamAV is installed as a prerequisite for this test

    CLAMAVBINARY=$(command -v clamscan)
    if [ ! "${CLAMAVBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; SKIPREASON="No ClamAV binary found"; fi
    Register --test-no CUST-9020 --preqs-met ${PREQS_MET} --skip-reason "${SKIPREASON}" --weight M --network NO --category security --description "Compleasy check anti-virus version and last update"
    if [ ${SKIPTEST} -eq 0 ]; then
        # Set variable to zero, to indicate that we have no problems found (yet)
        FOUNDPROBLEM=0
        # Check the version of the installed antivirus software
        AV_VERSION_FULL=$(freshclam -V 2>/dev/null | grep "ClamAV")
        AV_VERSION=$(echo ${AV_VERSION_FULL} | cut -d'/' -f1)
        if [ ! "${AV_VERSION}" = "" ]; then
            LogText "ClamAV version: ${AV_VERSION}"
            Display --indent 2 --text "ClamAV version" --result "${AV_VERSION}" --color GREEN
            Report "clamav_version=${AV_VERSION}"
        else
            LogText "ClamAV version not found"
            Display --indent 2 --text "ClamAV version not found" --result "${STATUS_WARNING}" --color YELLOW
            ReportWarning "${TEST_NO}" "ClamAV version not found" "text:Check if ClamAV is installed"
            FOUNDPROBLEM=1
        fi

        # Check the last update of the antivirus software
        # freshclam -V example output: ClamAV 0.103.11/27350/Sun Jul 28 10:25:11 2024
        AV_VERSION_FULL=$(freshclam -V 2>/dev/null | grep "ClamAV")
        AV_UPDATE=$(echo ${AV_VERSION_FULL} | cut -d'/' -f3-)
        if [ ! "${AV_UPDATE}" = "" ]; then
            LogText "ClamAV last update: ${AV_UPDATE}"
            Display --indent 2 --text "ClamAV last update" --result "${AV_UPDATE}" --color GREEN
            Report "clamav_last_update=${AV_UPDATE}"
        else
            LogText "ClamAV last update not found"
            Display --indent 2 --text "ClamAV last update not found" --result "${STATUS_WARNING}" --color YELLOW
            ReportWarning "${TEST_NO}" "ClamAV last update not found" "text:Check if ClamAV is installed"
            FOUNDPROBLEM=1
        fi

        if [ ${FOUNDPROBLEM} -eq 0 ]; then
            Display --indent 2 --text "- Checking if everything is OK..." --result "${STATUS_OK}" --color GREEN
        else
            Display --indent 2 --text "- Checking if everything is OK..." --result "${STATUS_WARNING}" --color RED
            ReportSuggestion "${TEST_NO}" "This is a suggestion"
        fi
    fi

#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#
#================================================================================
# Compleasy - Linux Server auditing solution https://github.com/compleasy/compleasy
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
