# Generated by Django 4.2.14 on 2024-07-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fullreport_created_at_licensekey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullreport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
    ]
