# Generated by Django 4.2.14 on 2024-07-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_created_at_device_licensekey_device_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DiffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
