# Generated by Django 4.2.14 on 2024-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fullreport_options_diffreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_query', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRuleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rules', models.ManyToManyField(to='api.policyrule')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='policy_ruleset',
            field=models.ManyToManyField(blank=True, related_name='devices', to='api.policyruleset'),
        ),
    ]
