# Generated by Django 4.2.14 on 2024-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_policyrule_policyruleset_device_policy_ruleset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='report',
        ),
        migrations.AddField(
            model_name='device',
            name='compliant',
            field=models.BooleanField(default=True),
        ),
    ]
