# Generated by Django 4.2.14 on 2024-08-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_device_report_device_compliant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='policy_ruleset',
            new_name='rulesets',
        ),
    ]
