# Generated by Django 4.2.16 on 2025-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_policy_ruleset_device_rulesets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostid2',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='licensekey',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['licensekey', 'hostid'], name='api_device_license_37d658_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['licensekey', 'hostid2'], name='api_device_license_5892d8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_update'], name='api_device_last_up_79d3db_idx'),
        ),
    ]
