# Generated by Django 4.2.16 on 2025-11-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_extend_activity_ignore_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enrolled', 'Device Enrolled')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='activityignorepattern',
            new_name='api_activit_organiz_ced1fb_idx',
            old_name='api_activi_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='activityignorepattern',
            new_name='api_activit_organiz_bba325_idx',
            old_name='api_activi_organiz_event_idx',
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', '-created_at'], name='api_devicee_device__e9a38f_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type', '-created_at'], name='api_devicee_event_t_4e6b6c_idx'),
        ),
    ]
