# Generated by Django 4.2.16 on 2025-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_deviceevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_ssl_errors', models.BooleanField(default=False)),
                ('overwrite_lynis_profile', models.BooleanField(default=False)),
                ('additional_packages', models.CharField(default='rkhunter auditd', max_length=255)),
                ('skip_tests', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Settings',
                'verbose_name_plural': 'Enrollment Settings',
            },
        ),
    ]
