# Generated by Django 4.2.16 on 2025-11-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_enrollmentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='api.enrollmentsettings')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
