# Generated by Django 4.2.16 on 2025-11-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_enrollmentplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSkipTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_tests_entries', to='api.enrollmentsettings')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
