# Generated by Django 4.2.16 on 2025-11-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_migrate_skip_tests_to_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_packages_entries', to='api.enrollmentsettings')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
