# Generated by Django 4.2.16 on 2025-11-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_default_trikusec_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('enrolled', 'Device Enrolled'), ('deleted', 'Device Deleted'), ('license_changed', 'License Changed')], db_index=True, max_length=50),
        ),
    ]
