# Generated by Django 4.2.16 on 2025-11-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_deviceevent_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffreport',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diffreport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device'),
        ),
    ]
