import pytest
from django.contrib.auth.models import User
from api.models import LicenseKey, Device, FullReport, DiffReport, Organization
from factory import Faker, SubFactory, LazyAttribute
from factory.django import DjangoModelFactory


class UserFactory(DjangoModelFactory):
    class Meta:
        model = User
        django_get_or_create = ('username',)

    username = Faker('user_name')
    email = Faker('email')
    password = Faker('password')


class OrganizationFactory(DjangoModelFactory):
    class Meta:
        model = Organization
        django_get_or_create = ('slug',)

    name = Faker('company')
    slug = LazyAttribute(lambda obj: obj.name.lower().replace(' ', '-')[:50])


class LicenseKeyFactory(DjangoModelFactory):
    class Meta:
        model = LicenseKey
        django_get_or_create = ('licensekey',)

    licensekey = Faker('uuid4')
    name = Faker('word')
    organization = SubFactory(OrganizationFactory)
    created_by = SubFactory(UserFactory)
    max_devices = None  # Unlimited by default
    is_active = True


class DeviceFactory(DjangoModelFactory):
    class Meta:
        model = Device

    licensekey = SubFactory(LicenseKeyFactory)
    hostid = Faker('uuid4')
    hostid2 = Faker('uuid4')
    hostname = Faker('hostname')
    os = 'Linux'
    distro = 'Ubuntu'
    distro_version = '22.04'
    lynis_version = '3.0.0'
    warnings = 0
    compliant = True


@pytest.fixture
def test_user(db):
    """Create a test user."""
    return UserFactory()


@pytest.fixture
def test_license_key(db, test_user):
    """Create a test license key."""
    # Get or create default organization
    default_org, _ = Organization.objects.get_or_create(
        slug='default',
        defaults={'name': 'Default Organization', 'is_active': True}
    )
    return LicenseKeyFactory(
        created_by=test_user,
        licensekey='deadbeef-cafebabe-00000123',  # Lynis-compliant format [a-f0-9-]
        name='Test License',
        organization=default_org
    )


@pytest.fixture
def test_device(db, test_license_key):
    """Create a test device."""
    return DeviceFactory(
        licensekey=test_license_key,
        hostid='test-host-id-1',
        hostid2='test-host-id-2'
    )


@pytest.fixture
def sample_lynis_report():
    """Sample Lynis report data for testing."""
    return """# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2024-01-01T10:00:00
report_datetime_end=2024-01-01T10:05:00
hostname=test-server
os=Linux
os_fullname=Ubuntu
os_version=22.04
lynis_version=3.0.0
warning_count=5
suggestion_count=10
test_skip_always=CRYP-7902
kernel_version=5.15.0
boot_mode=UEFI
hardening_index=65
"""


@pytest.fixture
def sample_lynis_report_updated():
    """Updated sample Lynis report data for testing diff generation."""
    return """# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2024-01-01T11:00:00
report_datetime_end=2024-01-01T11:05:00
hostname=test-server
os=Linux
os_fullname=Ubuntu
os_version=22.04
lynis_version=3.0.1
warning_count=3
suggestion_count=8
test_skip_always=CRYP-7902
kernel_version=5.15.0
boot_mode=UEFI
hardening_index=70
"""


@pytest.fixture
def sample_lynis_report_minimal():
    """Minimal Lynis report data for basic testing."""
    return """# Lynis Report
report_version_major=1
report_version_minor=0
hostname=minimal-test
os=Linux
lynis_version=3.0.0
"""


@pytest.fixture
def real_lynis_report():
    """
    Load real Lynis report from fixture file.
    
    This fixture loads a real Lynis report generated by the Lynis client.
    The report file is located at src/api/fixtures/lynis-report.dat.
    
    If the fixture file doesn't exist, the test will be skipped.
    """
    import os
    from pathlib import Path
    
    # Get the path to the fixture file
    # conftest.py is in src/, fixtures are in src/api/fixtures/
    base_dir = Path(__file__).parent
    fixture_path = base_dir / 'api' / 'fixtures' / 'lynis-report.dat'
    
    if not fixture_path.exists():
        pytest.skip(f"Real Lynis report fixture not found at {fixture_path}. "
                    f"Run 'scripts/extract-lynis-report.sh' to generate it.")
    
    # Read the report file
    with open(fixture_path, 'r', encoding='utf-8', errors='ignore') as f:
        report_content = f.read()
    
    if not report_content.strip():
        pytest.skip(f"Real Lynis report fixture is empty at {fixture_path}")
    
    return report_content

